DROP TABLE IF EXISTS dwh.listings_actual;
CREATE TABLE IF NOT EXISTS dwh.listings_actual (
    listing_id UInt64,
    listing_url String,
    price Decimal(18,2),
    price_per_sqm Decimal(18,2),
    mortgage_rate Float32,
    address String,
    address_id UInt64,
    area Float64,
    rooms UInt8,
    floor UInt8,
    description String DEFAULT '',
    published_date DateTime DEFAULT toDateTime('1970-01-01'),
    updated_date DateTime DEFAULT toDateTime('1970-01-01'),
    seller_id UInt64,
    seller_name_hash String,
    company_name String DEFAULT '',
    company_id UInt64,
    property_type Enum8('layout' = 2, 'townhouse' = 5, 'Unknown' = 6, 'house' = 3, 'flat' = 1, 'room' = 4),
    category Enum8('Unknown' = 2, 'living' = 1),
    house_floors UInt8,
    deal_type Enum8('sale' = 2, 'lease' = 3, 'Unknown' = 1, 'rent' = 4) DEFAULT 'Unknown',
    discount_status Enum8('Active' = 3, 'Expired' = 4, 'Unknown' = 1, 'None' = 2, 'discount_received' = 5) DEFAULT 'Unknown',
    discount_value Float64 DEFAULT 0,
    placement_paid UInt8 DEFAULT 0,
    big_card UInt8 DEFAULT 0,
    pin_color UInt8 DEFAULT 0,
    longitude Float64,
    latitude Float64,
    subway_distances Array(Float64) DEFAULT [],
    subway_names Array(String) DEFAULT [],
    photo_urls Array(String),
    monthly_payment Decimal(18,2) DEFAULT 0,
    advance_payment Decimal(18,2) DEFAULT 0,
    auction_status Float64,
    uid UUID,
    platform_id UInt8,
    created_at DateTime,
    seller_type Enum8('AGENT' = 5, 'AGENCY' = 2, 'DEVELOPER' = 1, 'OWNER' = 3, 'UNKNOWN' = 6, 'PRIVATE_AGENT' = 4) DEFAULT 'UNKNOWN',
    flat_type Enum8('SECONDARY' = 1, 'NEW_FLAT' = 2, 'UNKNOWN' = 4, 'NEW_SECONDARY' = 3) DEFAULT 'UNKNOWN',
    height Float64,
    area_rooms Float64,
    previous_price Float64,
    renovation_offer String,
    balcony_type Enum8('BALCONY' = 1, 'LOGGIA' = 2, 'BALCONY__LOGGIA' = 4, 'TWO_BALCONY' = 5, 'UNKNOWN' = 6, 'TWO_LOGGIA' = 3) DEFAULT 'UNKNOWN',
    window_view Enum8('YARD' = 1, 'YARD_STREET' = 2, 'STREET' = 3, 'UNKNOWN' = 4) DEFAULT 'UNKNOWN',
    built_year_offer UInt8,
    building_state Enum8('UNFINISHED' = 1, 'HAND_OVER' = 2, 'UNKNOWN' = 3) DEFAULT 'UNKNOWN',
    type_house_offer Enum8('BRICK' = 2, 'MONOLIT' = 1, 'PANEL' = 4, 'UNKNOWN' = 6, 'MONOLIT_BRICK' = 3, 'WOOD' = 5) DEFAULT 'UNKNOWN'
)
ENGINE = MergeTree
ORDER BY (listing_id);
