version: '3.8'

services:
  clickhouse:
    image: sergandri/clickhouse-storage:latest
    container_name: clickhouse-server
    ports:
      - "${CLICKHOUSE_HTTP_PORT:-8123}:8123"
      - "${CLICKHOUSE_PORT:-9000}:9000"
    environment:
      CLICKHOUSE_USER: "${CLICKHOUSE_USER:-default}"
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD:-password}"
    volumes:
      - ./config/clickhouse-server-config.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - clickhouse_data:/var/lib/clickhouse
    restart: always

volumes:
  clickhouse_data:
