name: Deploy ClickHouse

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        docker build -t your_dockerhub_user/clickhouse-storage:latest .
        docker push your_dockerhub_user/clickhouse-storage:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull your_dockerhub_user/clickhouse-storage:latest
          docker-compose up -d
