name: Deploy ClickHouse

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: List files in workspace
      run: |
        pwd
        ls -al
        ls -al config/
        ls -al init/

    - name: Rsync project files to server
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete --exclude '.git' --exclude 'data/' --exclude 'logs/'
        path: ./
        remote_path: "/home/${{ secrets.SERVER_USER }}/clickhouse/"
        remote_host: ${{ secrets.SERVER_HOST }}
        remote_user: ${{ secrets.SERVER_USER }}
        remote_key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Deploy ClickHouse on server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        env:
          CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
          CLICKHOUSE_MS_PASSWORD: ${{ secrets.CLICKHOUSE_MS_PASSWORD }}
        script: |
          cd ~/clickhouse
          sudo docker-compose down || true
          sudo docker-compose up -d
