name: Deploy ClickHouse

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t sergandri/clickhouse-storage:latest .
        docker push sergandri/clickhouse-storage:latest

    - name: Copy docker-compose.yml to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "docker-compose.yml"
        target: "~/deploy/"

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PASSWORD }}
        env: |
          CLICKHOUSE_HTTP_PORT=8123
          CLICKHOUSE_PORT=9000
          CLICKHOUSE_USER=${{ secrets.CLICKHOUSE_USER }}
          CLICKHOUSE_PASSWORD=${{ secrets.CLICKHOUSE_PASSWORD }}
        script: |
          cd ~/deploy
          docker pull sergandri/clickhouse-storage:latest
          docker-compose up -d
