name: Deploy ClickHouse

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t sergandri/clickhouse-storage:latest .
        docker push sergandri/clickhouse-storage:latest

    - name: Create project directory on server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PASSWORD }}  # Используем SSH-ключ из SERVER_PASSWORD
        script: |
          sudo mkdir -p /home/sergandri/projects/clickhouse_dwh/config
          sudo mkdir -p /home/sergandri/projects/clickhouse_dwh/data

    - name: Copy docker-compose.yml to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PASSWORD }}  # Используем SSH-ключ из SERVER_PASSWORD
        source: "docker-compose.yml"
        target: "/home/sergandri/projects/clickhouse_dwh/docker-compose.yml"

    - name: Copy clickhouse-server-config.xml to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PASSWORD }}
        source: "config/clickhouse-server-config.xml"
        target: "/home/sergandri/projects/clickhouse_dwh/config/clickhouse-server-config.xml"

    - name: Copy users.xml to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PASSWORD }}
        source: "config/users.xml"
        target: "/home/sergandri/projects/clickhouse_dwh/config/users.xml"

    - name: Remove existing ClickHouse container (if any)
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker rm -f clickhouse-server || true

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PASSWORD }}
        envs: |
          CLICKHOUSE_HTTP_PORT=${{ secrets.CLICKHOUSE_HTTP_PORT }}
          CLICKHOUSE_PORT=${{ secrets.CLICKHOUSE_PORT }}
          CLICKHOUSE_USER=${{ secrets.CLICKHOUSE_USER }}
          CLICKHOUSE_PASSWORD=${{ secrets.CLICKHOUSE_PASSWORD }}
        script: |
          cd /home/sergandri/projects/clickhouse_dwh
          docker pull sergandri/clickhouse-storage:latest
          docker-compose up -d
