name: Deploy ClickHouse

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker and Docker Compose on server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}  # IP или доменное имя вашего сервера
        username: ${{ secrets.SERVER_USER }}  # Имя пользователя для SSH-подключения
        key: ${{ secrets.SERVER_SSH_KEY }}  # Приватный SSH-ключ для аутентификации
        script: |
          sudo apt-get update -y
          if ! command -v docker &> /dev/null
          then
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
          fi
          if ! command -v docker-compose &> /dev/null
          then
            sudo apt-get install -y python3-pip
            sudo pip3 install docker-compose
          fi

    - name: Copy project files to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "."
        target: "/home/${{ secrets.SERVER_USER }}/projects/clickhouse_dwh/"
        overwrite: true

    - name: Deploy ClickHouse on server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/${{ secrets.SERVER_USER }}/projects/clickhouse_dwh
          sudo docker-compose down || true
          sudo docker-compose up -d
